title: "Team Allocations - {{ LOCATION YEAR e.g. Brisbane 2024 }}"
labels: ["Team allocation"]
body:
  - type: textarea
    id: intro
    attributes:
      label: "Hi All,"
      description: This is the intro - you can leave as is, or edit if needed
      value: |
        We want teams to be ready to go on the day, that's why we now pre-allocate the teams. See the team allocations below.
                        
        👑 [Idea Champion](https://www.ssw.com.au/rules/brainstorming-idea-champion/) - The person who will advocate for the idea after the brainstorming day, until it is officially approved or parked.
        
        Let me know if there are any concerns 😊
        
        1. Review your team idea and prepare for the day.
    validations:
      required: true
  - type: textarea
    id: team-list
    attributes:
      label: "Here are the teams:"
      description: Duplicate this for each team, and fill in the placeholders
      value: |
        ## Team 1 - [{{ TEAM NAME }}]({{ URL TO GITHUB DISCUSSION }})
        [Presentation Template + Other Documentation](https://sswcom.sharepoint.com/:f:/s/BrisbaneBrainstorming2024/EgAMWryDd1NPlR93TPStNQYBayt-mRH7XPK1qIzahJ14dQ?e=0aUHXE)
        
        ⛺ Stakeholders: 
        - {{ STAKEHOLDER 1 }}
        - {{ STAKEHOLDER 2 }}
        - ...
        
        🏀 Team:
        - {{ MEMBER 1 }}
        - {{ MEMBER 2 }}
        - ...

        👑 Idea Champion:
        - {{ NAME }}
    validations:
      required: true
