title: "Team Allocations - {{ LOCATION YEAR e.g. Brisbane 2024 }}"
labels: ["Team allocation"]
body:
  - type: textarea
    id: improvements
    attributes:
      label: Edit this as needed
      description: Not needed
      value: |
        ### Hi All
        We want teams to be ready to go on the day, that's why we now pre-allocate the teams. Here are the team allocations.
        
        Stakeholders – People you should have corridor conversations with prior to as well as throughout the day. They would also be a good choice for your PowerPoint Test Please.
                
        Idea Champion - The person who will advocate for the idea after the brainstorming day, until it is officially approved or parked.
        
        Let me know if there are any concerns 😊
        
        1. Review your team idea and prepare for the day.
    validations:
      required: true
