name: Bug Report
description: File a bug report
title: "[Bug]: "
body:
  - type: markdown
    attributes:
      value: |
        Start here to request/create a new page
  - type: textarea
    id: template
    attributes:
      label: Template
      description: Style/format - Link a design template or a page to copy (e.g. a Consulting page or a Training page).
      placeholder: Link your template here
      value: "{{ PAGE TEMPLATE }}"
    validations:
      required: true
  - type: textarea
    id: template
    attributes:
      label: Template
      description: Style/format - Link a design template or a page to copy (e.g. a Consulting page or a Training page).
      placeholder: Link your template here
      value: "{{ PAGE TEMPLATE }}"
    validations:
      required: true
