name: New webpage
description: Start here to request/create a new page
title: "✨ [Title]: "
body:
 - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: question
    attributes:
      label: "Template"
      description: Link a design template or a page to copy (e.g. a Consulting page or a Training page).
      placeholder: {{ PAGE TEMPLATE }}
      value: "A bug happened!"
    validations:
      required: true
