name: ✨ New Webpage
description: Start here to request/create a new page
title: "✨ [Title]: "
body:
  - type: markdown
    attributes:
      value: |
        Start here to request/create a new page
  - type: textarea
    id: template
    attributes:
      label: 1. Template
      description: Style/format - Link a design template or a page to copy (e.g. a Consulting page or a Training page).
      placeholder: Link your template here
      value: "{{ PAGE TEMPLATE }}"
    validations:
      required: true
  - type: textarea
    id: URI
    attributes:
      label: 2. URI
      description: Use keywords and make it [as short as possible](https://www.ssw.com.au/rules/create-friendly-short-urls/). Use [kebab case](https://www.ssw.com.au/rules/use-dashes-in-urls) (e.g. use-dashes-and-lowercase)
      placeholder: write-your-uri-here
      value: "{{ URI }}"
    validations:
      required: true
  - type: textarea
    id: title
    attributes:
      label: 3. Title
      description: Must read well and include keywords (Google-able). Must be under 60 characters  
      placeholder: Page title
      value: "{{ TITLE }}"
    validations:
      required: true
