name: ✨ New Webpage
description: Start here to request/create a new page
title: "✨ [Title]: "
body:
  - type: markdown
    attributes:
      value: |
        Start here to request/create a new page
  - type: textarea
    id: template
    attributes:
      label: 1. Template
      description: Style/format - Link a design template or a page to copy (e.g. a Consulting page or a Training page).
      placeholder:
      value: "{{ PAGE TEMPLATE }}"
    validations:
      required: true
  - type: textarea
    id: URI
    attributes:
      label: 2. URI
      description: "Details: Concise and including keywords. Use [kebab case](https://www.ssw.com.au/rules/use-dashes-in-urls) (e.g. use-dashes-and-lowercase). 
      
      Length: [As short as possible](https://www.ssw.com.au/rules/create-friendly-short-urls/)"
      placeholder:
      value: "{{ URI }}"
    validations:
      required: true
  - type: textarea
    id: title
    attributes:
      label: 3. Title
      description: "Details: Must read well and include keywords (Google-able).
      
      Length: Must be under 60 characters"  
      placeholder:
      value: "{{ TITLE }}"
    validations:
      required: true
  - type: textarea
    id: meta
    attributes:
      label: 4. Meta description
      description: "Details: For search engines - summary of the page using the important keywords.
      
      Length: under 150 characters. 
      
      Tip: You can give ChatGPT your content and ask for a meta description."
      placeholder:
      value: "{{ META DESCRIPTION }}"
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: 5. Related URLs
      description: If applicable, related pages on the SSW website.
      placeholder:
      value: "{{ RELATED URLS }}"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "**Content**
      "
  - type: textarea
    id: content
    attributes:
      label: 6. Content
      description: If applicable, related pages on the SSW website.
      placeholder:
      value: "{{ RELATED URLS }}"
    validations:
      required: true
